import { Inter_Tight } from 'next/font/google'
import './globals.css'
import { Unbounded } from 'next/font/google';

const unbounded = Unbounded({
  subsets: ['latin'],
  weight:['200', '300', '400', '600'],
  variable: '--font-unbounded',
  // display: "swap"
})
const inter = Inter_Tight({ 
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata = {
  title: 'Influenzilla',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${inter.className} ${unbounded.variable}`}>{children}</body>
    </html>
  )
}
